name: production-deploy

on:
  push:
    branches:
      - main

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  production-deploy:
    runs-on: self-hosted

    steps:
      - name: Check out latest commit
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/web-api

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/web-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/web-api:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Get kubeconfig from github secrets
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
          sudo chown $(id -u):$(id -g) $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Rollout Updated Web API Deployment
        run: |
          kubectl rollout restart deployment web-api
          kubectl rollout status deployment web-api --timeout=60s